version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-conf:/var/log/nginx
      - nginx-conf:/var/www/html
      - php:/apps
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=portofolio_db
      - MYSQL_USER=porto_user
      - MYSQL_PASSWORD=portoPassword
    networks:
      - internal
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-data:/var/log/mysql
    depends_on:
    - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    networks:
      - internal
    volumes:
      - php:/var/www/html
      - php:/var/log/fpm-php

volumes:
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /apps/nginx/

  php:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /apps/php/

  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /apps/mysql/

networks:
  internal:
    driver: bridge
