apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-subnet: "sn-nonk8s-bpr-preprod"
  name: {{ include "ad1-adm-main.fullname" . }}
  labels:
    {{- include "ad1-adm-main.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.IPLoadBalancer }}
  {{- end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "ad1-adm-main.selectorLabels" . | nindent 4 }}
