---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db-porto
type: Opaque
data:
 MYSQL_USER: cG9ydG9fdXNlcgo=
 MYSQL_DATABASE: cG9ydG9mb2xpb2Ri
 MYSQL_PASSWORD: cGFzc3dvcmQ=
 MYSQL_ROOT_PASSWORD: cGFzc3dvcmRQb3J0bw==
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /apps/mysql
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   selector:
#     matchLabels:
#       app: porto-mysql
#   storageClassName: standard-rwo
# ---
# Source: porto-mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: porto-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    name: porto-mysql
---
# Source: porto-mysql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: porto-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: porto-mysql
  template:
    metadata:
      labels:
        name: porto-mysql
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: porto-mysql
          image: mysql:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_USER
              valueFrom:
                  secretKeyRef:
                      key: MYSQL_USER
                      name: secret-db-porto
            - name: MYSQL_DATABASE
              valueFrom:
                  secretKeyRef:
                      key: MYSQL_DATABASE
                      name: secret-db-porto
            - name: MYSQL_PASSWORD
              valueFrom:
                  secretKeyRef:
                      key: MYSQL_PASSWORD
                      name: secret-db-porto
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                      key: MYSQL_ROOT_PASSWORD
                      name: secret-db-porto
          resources:
            limits:
              memory: "1G"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "0.1"
      #     volumeMounts:
      #       - name: mysql-pv
      #         mountPath: /var/lib/mysql
      #       - name: mysql-pv
      #         mountPath: /var/www/html
      # volumes:
      # - name: mysql-pv
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
---
# Source: porto/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: porto-mysql
  labels:
    name: porto-mysql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: porto-mysql
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
