FROM alpine:latest

RUN apk add openjdk8 \ 
        tzdata \
        tar \
    && apk update

COPY apache-tomcat-8.5.91.tar.gz . 

RUN mkdir /usr/local/tomcat \
    && mkdir /usr/local/tomcat/tmp \
    && tar --strip-components=1 -xf apache-tomcat-8.5.91.tar.gz -C /usr/local/tomcat

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
ENV CATALINA_HOME=/usr/local/tomcat/
ENV CATALINA_PID=/usr/local/tomcat/temp/tomcat.pid

